spring:
  application:
    name: sms-system
  datasource:
    url: jdbc:postgresql://localhost:5432/e_commerce_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      enabled: false

server:
  port: 8082
