logging:
  level:
    root: INFO
    com.e_commerce.order: DEBUG

spring:
  application:
    name: order-system
  datasource:
    url: jdbc:postgresql://localhost:5432/e_commerce_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  docker:
    compose:
      enabled: false

services:
  base-url: http://localhost:8080
  email-url: http://localhost:8081/v1/email/{id}
  sms-url: http://localhost:8082/v1/sms/{id}
